---
name: Catalyst-Model-CDBI-Sweet
version: 0.05
author:
  - Christian Hansen <ch@ngmedia.com>
abstract: ~
license: perl
requires:
  Catalyst: 5.24
  Class::DBI::Sweet: 0
provides:
  Catalyst::Model::CDBI::Sweet:
    file: lib/Catalyst/Model/CDBI/Sweet.pm
    version: 0.05
generated_by: Module::Build version 0.2607
